version: "3.8"

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  frontend:
    build:
      context: ..
      dockerfile: ./performance/Dockerfile
      network: host
      args:
        NPMRC: $NPMRC
        NEXT_PUBLIC_BPAPI_URI: ${NEXT_PUBLIC_BPAPI_URI:-https://www.beautypie-preview.com/graphql}
        NEXT_PUBLIC_API_URI_INTERNAL: ${NEXT_PUBLIC_API_URI_INTERNAL:-http://host.docker.internal:4000/graphql}
        BEAUTYPIE_BRANCH_NAME: $BEAUTYPIE_BRANCH_NAME
        CONTENTFUL_SPACE_ID: $CONTENTFUL_SPACE_ID
        CONTENTFUL_DELIVERY_API_KEY: $CONTENTFUL_DELIVERY_API_KEY
        CONTENTFUL_MANAGEMENT_API_KEY: $CONTENTFUL_MANAGEMENT_API_KEY
        ROBOTS_FILE_OVERRIDE: $ROBOTS_FILE_OVERRIDE
        GIT_COMMIT_SHA: $GIT_COMMIT_SHA
        BUILDKIT_INLINE_CACHE: 1
    ports:
      - "3000:3000"
      - "9229:9229"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:v2.20.1
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:7.1.5
    container_name: grafana
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/grafana.ini/:/etc/grafana/grafana.ini
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    ports:
      - 3001:3000
    networks:
      - monitoring

  nodeexporter:
    image: prom/node-exporter:v0.18.1
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100
    networks:
      - monitoring
    labels:
      org.label-schema.group: "monitoring"
