global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: "frontend"
    metrics_path: /api/metrics
    static_configs:
      # external localhost:3000 target host from within docker
      - targets: ["host.docker.internal:3000"]
        labels:
          group: 'nextjs'
